/* file: echosrv.c

   Bare-bones single-threaded TCP server. Listens for connections
   on "ephemeral" socket, assigned dynamically by the OS.

   This started out with an example in W. Richard Stevens' book
   "Advanced Programming in the Unix Environment".  I have
   modified it quite a bit, including changes to make use of my
   own re-entrant version of functions in echolib.

   NOTE: See comments starting with "NOTE:" for indications of
   places where code needs to be added to make this multithreaded.
   Remove those comments from your solution before turning it in,
   and replace them by comments explaining the parts you have
   changed.

   Ted Baker
   February 2015

 */

#include "config.h"
/* not needed now, but will be needed in multi-threaded version */
#include "pthread.h"
#include "echolib.h"
#include "checks.h"
#include "list.h"

#define TRUE			1
#define FALSE			0
#define THREAD_POOL_SIZE	9

pthread_cond_t *mycond;
pthread_cond_t empty_cond = PTHREAD_COND_INITIALIZER;

pthread_cond_t async_cond = PTHREAD_COND_INITIALIZER;
pthread_mutex_t async_mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t mutex_lock = PTHREAD_MUTEX_INITIALIZER;
pthread_spinlock_t spin_lock_flag;

int lock_flag = 0;

static LIST_HEAD(threadpool);

struct thread_node {
	struct list_head list;
	int sockfd;
	int id;
}thread_node;

int sock_queue[20] = {0, };
int client_num = 0;

int serve_connection (int sockfd);
/* NOTE: You will need to completely rewrite this function, so
   that it hands off the connection to one of your server threads,
   moving the call to serve_connection() into the server thread
   body.  To do that, you will need to declare a lot of new stuff,
   including thread, mutex, and condition variable structures,
   functions, etc.  You can insert the new bode before and after
   this function, but you do not need to modify serve_connection()
   or anything else between it and the note in the main program
   body.  However, you are free to change anything in this file if
   you feel it is necessary for your design. */

void* server_handoff (void* data) {
	struct thread_node* temp = (struct thread_node*)data;
	int connfd;

	pthread_cond_signal(&async_cond);

	while(1) {
		pthread_cond_wait(&mycond[temp->id], &mutex_lock);
	
		while(1) {
			connfd = temp->sockfd;
			if(!serve_connection(connfd))
				break;
		}
		list_move_tail(&temp->list, &threadpool);
		
		pthread_spin_lock(&spin_lock_flag);
		if(lock_flag) {	
			lock_flag--;
			pthread_cond_signal(&empty_cond);
		}
		pthread_spin_unlock(&spin_lock_flag);
	}
}

/* the main per-connection service loop of the server; assumes
   sockfd is a connected socket */
int serve_connection (int sockfd) {
	ssize_t  n, result;
	char line[MAXLINE];
	connection_t conn;
	connection_init (&conn);
	conn.sockfd = sockfd;
	while (! shutting_down) {
		if ((n = readline (&conn, line, MAXLINE)) == 0) goto quit;
		/* connection closed by other end */
		if (shutting_down) goto quit;
		if (n < 0) {
			perror ("readline failed");
			goto quit;
		}
		result = writen (&conn, line, n);
		if (shutting_down) goto quit;
		if (result != n) {
			perror ("writen failed");
			goto quit;
		}
	}
quit:
	CHECK (close (conn.sockfd));
	return 0;
}

/* set up socket to use in listening for connections */
void open_listening_socket (int *listenfd) {
	struct sockaddr_in servaddr;
	const int server_port = 0; /* use ephemeral port number */
	socklen_t namelen;
	memset (&servaddr, 0, sizeof(struct sockaddr_in));
	servaddr.sin_family = AF_INET;
	/* htons translates host byte order to network byte order; ntohs
	   translates network byte order to host byte order */
	servaddr.sin_addr.s_addr = htonl (INADDR_ANY);
	servaddr.sin_port = htons (server_port);
	/* create the socket */
	CHECK (*listenfd = socket(AF_INET, SOCK_STREAM, 0))
		/* bind it to the ephemeral port number */
		CHECK (bind (*listenfd, (struct sockaddr *) &servaddr, sizeof (servaddr)));
	/* extract the ephemeral port number, and put it out */
	namelen = sizeof (servaddr);
	CHECK (getsockname (*listenfd, (struct sockaddr *) &servaddr, &namelen));
	fprintf (stderr, "server using port %d\n", ntohs(servaddr.sin_port));
}

/* handler for SIGINT, the signal conventionally generated by the
   control-C key at a Unix console, to allow us to shut down
   gently rather than having the entire process killed abruptly. */ 
void siginthandler (int sig, siginfo_t *info, void *ignored) {
	shutting_down = 1;
}

void install_siginthandler () {
	struct sigaction act;
	/* get current action for SIGINT */
	CHECK (sigaction (SIGINT, NULL, &act));
	/* add our handler */
	act.sa_sigaction = siginthandler;
	/* update action for SIGINT */
	CHECK (sigaction (SIGINT, &act, NULL));
}

int main (int argc, char **argv) {
	int connfd, listenfd;
	socklen_t clilen;
	struct sockaddr_in cliaddr;
	struct thread_node* node[THREAD_POOL_SIZE];
	struct thread_node* pos = NULL;
	int status, current = 0;
	pthread_t thread[THREAD_POOL_SIZE];

	mycond = (pthread_cond_t *)malloc(sizeof(pthread_cond_t) * THREAD_POOL_SIZE);
	pthread_spin_init(&spin_lock_flag, 1);

	for(int i = 0; i < THREAD_POOL_SIZE; i++) {
		node[i] = (struct thread_node *)malloc(sizeof(struct thread_node));
		node[i]->id = i;
		list_add_tail(&node[i]->list, &threadpool);
		pthread_mutex_lock(&async_mutex);
		if(pthread_create(&thread[i], NULL, server_handoff, (void *)node[i]) < 0 ) {
			perror("cannot create thread\n");
			exit(1);
		}	
		pthread_cond_wait(&async_cond, &async_mutex);
		pthread_mutex_unlock(&async_mutex);
	}
	//create thread pool

	install_siginthandler();
	open_listening_socket (&listenfd);
	CHECK (listen (listenfd, 4));
	/* allow up to 4 queued connection requests before refusing */
	while (! shutting_down) {
		errno = 0;
		clilen = sizeof (cliaddr); /* length of address can vary, by protocol */
		if ((connfd = accept (listenfd, (struct sockaddr *) &cliaddr, &clilen)) < 0) {
			if (errno != EINTR) ERR_QUIT ("accept"); 
			/* otherwise try again, unless we are shutting down */
		} 
		else {
			sock_queue[client_num++] = connfd;
			if(list_empty(&threadpool)) {
				pthread_spin_lock(&spin_lock_flag);
				lock_flag++;
				pthread_spin_unlock(&spin_lock_flag);
				pthread_cond_wait(&empty_cond, &mutex_lock);
			}
			list_for_each_entry(pos, &threadpool, list) {
				if(sock_queue[current] && current < client_num) {
					pos->sockfd = sock_queue[current++];
					list_del_init(&pos->list);
					pthread_cond_signal(&mycond[pos->id]);
					break;
				}
				else
					break;
			}	
		}
	}

	CHECK (close (listenfd));
	for(int i = 0; i < THREAD_POOL_SIZE; i++)
		pthread_join(thread[i], (void *)&status);
	
	return 0;

}
